AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 25
Style/StringLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
